### PR TITLE
Check rsync version

### LINKED ISSUE #42: Check rsync version
Ingestor is not working on RHEL9.

RHEL9 use rsync version 3.2.3 while RHEL8 use 3.1.3. They changed some commandline options between this two versions.
Ingestor currently execute on RHEL8 >`rsync -e ssh -q -avxz --progress --msgs2stderr  /path....`

This is not working anymore on RHEL9

The command line which work on RHEL9 > `rsync -e ssh -avxz --progress --stderr=error  /path....`

So the flag `-q` after ssh need to be removed and the `--msgs2stderr` changes to `--stderr=error`

### PR DESCRIPTION
**Pull request by kavir1698**
Will fix #42

### CODE REVIEW

File: datasetIngestor/syncDataToFileserver_unix.go [hunk 1]
```diff
@@ -9,6 +9,8 @@ import (
 	"os"
 	"os/exec"
 	"strings"
+	version "github.com/mcuadros/go-version"
```
Comment (minottic) [inline datasetIngestor/syncDataToFileserver_unix.go:12]: is this needed by this PR?

File: datasetIngestor/syncDataToFileserver_unix.go [hunk 2]
```diff
@@ -21,27 +23,49 @@ func SyncDataToFileserver(datasetId string, user map[string]string, RSYNCServer
...
 	}
-	// show rsync's output
-	// cmd.Stdout = os.Stdout
-	cmd.Stderr = os.Stderr
-
-	log.Printf("Running %v.\n", cmd.Args)
-	err = cmd.Run()
+	
+	// Check rsync version and adjust command accordingly
+	var rsyncCmd *exec.Cmd
```
Comment (minottic) [inline datasetIngestor/syncDataToFileserver_unix.go:33]: this feels a little as code duplicaction. To me what changes is only that in some cases we have to do `ssh -q`. What if we maybe just make this a variable and simplify the IF?

Comment (minottic) [reply datasetIngestor/syncDataToFileserver_unix.go:33]: (same for the --files-from, though slightly more complex, so we can keep it as is

**Review by minottic — COMMENTED** [review]
going forward we could see if there is a go rsync wrapper. 

Would it be easy to add tests on the functions that use rsync to see if they still fail?

File: datasetIngestor/syncDataToFileserver_unix.go (hunk 2 above)
Comment (kavir1698) [reply datasetIngestor/syncDataToFileserver_unix.go:33]: > this feels a little as code duplicaction. To me what changes is only that in some cases we have to do ssh -q. What if we maybe just make this a variable and simplify the IF?

it both adding/removing `-q` and replacing `--stderr=error` and `--msgs2stderr`

**Comment by kavir1698** [comment]
> going forward we could see if there is a go rsync wrapper.
> 
> Would it be easy to add tests on the functions that use rsync to see if they still fail?

After a little searching, I found a few rsync wrapper but they don't seem to be well maintained.

I tested the ingest manually and it worked. Testing `SyncDataToFileserver` would be a bit tricky with a lot of mocking.

File: datasetIngestor/syncDataToFileserver_unix.go (hunk 2 above)
Comment (minottic) [reply datasetIngestor/syncDataToFileserver_unix.go:33]: but at least for the version check, one could simply do: 

if version.Compare(versionNumber, "3.2.3", ">=") { ssh="ssh -q"} else {ssh="ssh}

and then just pass this variable outside of the if to the exec command

Comment (minottic) [reply datasetIngestor/syncDataToFileserver_unix.go:33]: but at least for the version check, one could simply do:

if version.Compare(versionNumber, "3.2.3", ">=") { ssh="ssh -q"} else {ssh="ssh}

and then just pass this variable outside of the if to the exec command

Comment (kavir1698) [reply datasetIngestor/syncDataToFileserver_unix.go:33]: I've change them now

**Review by minottic — APPROVED** [review]

File: datasetIngestor/syncDataToFileserver_unix.go [hunk 3]
```diff
@@ -21,27 +23,52 @@ func SyncDataToFileserver(datasetId string, user map[string]string, RSYNCServer
...
 	if absFileListing != "" {
-		cmd = exec.Command("/usr/bin/rsync", "-e", "ssh -q", "-avxzr", "--progress", "--msgs2stderr", "--files-from", absFileListing, fullSourceFolderPath, serverConnectString)
+		rsyncFlags = append(rsyncFlags, "-r", "--files-from", absFileListing)
 	}
-	// show rsync's output
-	// cmd.Stdout = os.Stdout
-	cmd.Stderr = os.Stderr
+	if version.Compare(versionNumber, "3.2.3", ">=") {
+		rsyncFlags = append(rsyncFlags, "--stderr=error")
+		rsyncCmd = exec.Command("/usr/bin/rsync", append(rsyncFlags, fullSourceFolderPath, serverConnectString)...)
```
Comment (minottic) [inline datasetIngestor/syncDataToFileserver_unix.go:40]: sorry, I missed this yesterday... since the rsyncCmd is the same in the `if` and `else` I think we can move it after the block.

If we do this, it will become easy (I guess) to do the rsyncFlags build in a function which can later be tested

Comment (kavir1698) [reply datasetIngestor/syncDataToFileserver_unix.go:40]: You didn't miss it yesterday, I just changed the code as I noticed a mistake in the code.

Comment (kavir1698) [reply datasetIngestor/syncDataToFileserver_unix.go]: It is now a separate function and fully tested

Comment (minottic) [reply datasetIngestor/syncDataToFileserver_unix.go]: thx!

**Review by minottic — APPROVED** [review]

File: datasetIngestor/syncDataToFileserver_unix.go [hunk 4]
```diff
@@ -21,27 +23,54 @@ func SyncDataToFileserver(datasetId string, user map[string]string, RSYNCServer
...
+func buildRsyncCmd(versionNumber, absFileListing, fullSourceFolderPath, serverConnectString string) *exec.Cmd {
+	rsyncFlags := []string{"-e", "ssh", "-avxz", "--progress"}
+	if absFileListing != "" {
+		rsyncFlags = append([]string{"-r", "--files-from", absFileListing}, rsyncFlags...)
+	}
+	if version.Compare(versionNumber, "3.2.3", ">=") {
+		rsyncFlags = append(rsyncFlags, "--stderr=error")
+		// Full command: /usr/bin/rsync -e ssh -avxz --progress -r --files-from <absFileListing> --stderr=error <fullSourceFolderPath> <serverConnectString>
+	} else {
+		rsyncFlags = append(rsyncFlags, "-q", "--msgs2stderr")
```
Comment (sbliven) [inline datasetIngestor/syncDataToFileserver_unix.go:71]: My mac has v 3.1.3 but doesn't support `--msgs2stderr`.

**Review by sbliven — APPROVED** [review]
Worked for me in -testenv from pmod7 (springdale 7.9) and ra-l-005 (rhel 8).

File: datasetIngestor/syncDataToFileserver_unix.go (hunk 4 above)
Comment (kavir1698) [reply datasetIngestor/syncDataToFileserver_unix.go:71]: Maybe we should reduce the threshold from 3.2.3?

**Comment by kavir1698** [comment]
Since it wasn't working on RHEL9 before, and now the problem is just not printing the output, and since Spencer needs to have the version here up to 2.2.0, I think it is safe that we merge this now and fix the printing problem in a later PR

File: datasetIngestor/syncDataToFileserver_unix.go (hunk 4 above)
Comment (kavir1698) [reply datasetIngestor/syncDataToFileserver_unix.go:71]: I'm not sure what to do here.

**Comment by sbliven** [comment]
Seems reasonable. 🚀

File: datasetIngestor/syncDataToFileserver_unix.go (hunk 4 above)
Comment (sbliven) [reply datasetIngestor/syncDataToFileserver_unix.go:71]: Let's leave it as an open issue
